# Use this when Prometheus runs on host (e.g. brew install prometheus)
# Target: localhost since API is also on host
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "cats-dogs-api"
    metrics_path: /metrics
    static_configs:
      - targets:
          - localhost:8000
