global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "cats-dogs-api"
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:8000  # Docker Desktop
          # For Linux: use 172.17.0.1:8000 or service IP
